#UNet 掩码生成器训练
model:
  base_learning_rate: 3e-05
  target: ldm.models.diffusion.mask_generator.Mask_Unet
  params:
    hint_channel: 5
    resolution: 512

    unet_config:
      target: ldm.modules.diffusionmodules.model.Model
      params:
        ch: 128
        in_channels: 128    #TODO:按照是否是扩散模型进行调节
        out_ch: 128
        attn_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        ch_mult: [1, 2, 4, 4 ]
        resolution: 2
        use_timestep: False  ##TODO:按照是否是扩散模型进行调节
        attn_type: "none"

data:
  target: test.DataModuleFromConfig
  params:
      batch_size: 1
      wrap: False
      test:
          target: ldm.data.mask_dresscode.OpenImageDataset
          params:
              state: test
              dataset_dir: datasets/dresscode


lightning:
  trainer:
    num_nodes: 1
    profiler: "simple"
    accelerator: 'ddp'
    gpus: "0"